<a href="https://colab.research.google.com/github/EmmanuelUdeA/CifradoDeCesar/blob/main/LABMatricesDis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
ximport numpy as np
import matplotlib.pyplot as plt
import bisect


In [ ]:
# LABORATORIO SPARSE MATRIX LOGICA 2 2023-1 UDEA
# REALIZADO POR EMMANUEL BUSTAMANTE VALBUENA

In [ ]:
#------------------------#

In [ ]:
#LABORATORIO 3

#1 Diccionario de Diccionarios

def add_to_dict(d, key1, key2, val):

    if key1 not in d:
        d[key1] = {}
    d[key1][key2] = val

    return d

In [ ]:
d = {}
add_to_dict(d, 10, 3,  "20")
add_to_dict(d, 1, 5,  "4")
add_to_dict(d, 1, 2, "14")
print(d)

{10: {3: '20'}, 1: {5: '4', 2: '14'}}


In [ ]:
# 2. Implementar el constructor y el metodo para llenar una matriz


def SparseMatrix2(m=None, **kwargs):

    import itertools

    def add_to_dict(d, key1, key2, val):

        if key1 not in d:
            d[key1] = {}
        d[key1][key2] = val
        return d


    class SparseMatrix2_class:

        def __init__(self, m=m, **kwargs):
            self.rows = {} # diccionario de entradas no nulas de la matriz
            self.shape = (0,0)  # define el tamaño de la matriz
            if m is not None: # si m no es nula. m es la matriz y se le agregan los valores
              for i,j in itertools.product(range(m.shape[0]),range(m.shape[1])):
                if m[i,j] != 0:# Si el valor es distinto de 0 se agrega a la matriz
                    add_to_dict(self.rows, i, j, m[i, j])
                    self.shape = (max(self.shape[0], i + 1), max(self.shape[1], j + 1))
                    #Se actualiza la matriz


        def sparseness_metric(self): # Metrica de una matriz, la cantidad de valores no nules, divido numero total de elementos

            #self.shape[0] * self.shape[1] # numero total de elementos
            metric = 1 - len(self.rows) / (self.shape[0] * self.shape[1]) # calculo de la metrica, el 1 es una buena practica de python para que el numero sea un punto flotante
            return metric

    return SparseMatrix2_class(**kwargs)

In [ ]:
import numpy as np

def random_sparse_matrix(size):
    m = np.random.randint(2, size=size)
    m = m * np.random.randint(10,size=size)
    return m

m = random_sparse_matrix((5,3))

sm = SparseMatrix2(m)
print(m.shape, sm.sparseness_metric())
m




(5, 3) 0.7333333333333334


array([[0, 0, 1],
       [1, 0, 6],
       [3, 0, 0],
       [0, 0, 0],
       [2, 3, 6]])

In [ ]:
s = SparseMatrix2(m)
print("rows", s.rows) # escribimos por filas
print("length of each row", [len(s.rows[i]) for i in list(s.rows.keys())]) # vector con la cantidad de elementos de las filas

rows {0: {2: 1}, 1: {0: 1, 2: 6}, 2: {0: 3}, 4: {0: 2, 1: 3, 2: 6}}
length of each row [1, 2, 1, 3]


In [ ]:
s = SparseMatrix2(None)
s.shape

(0, 0)

In [ ]:
# 3. Implementar metodo sense y Transpuesta

def SparseMatrix3(m=None, **kwargs):

    import itertools
    import numpy as np

    def add_to_dict(d, key1, key2, val):
        if key1 not in d:
            d[key1] = {}
        d[key1][key2] = val
        return d

    class SparseMatrix3_class:

        def __init__(self, m=m, **kwargs):
            self.rows = {} # diccionario de entradas no nulas de la matriz
            self.shape = (0,0)  # define el tamaño de la matriz
            if m is not None: # si m no es nula. m es la matriz y se le agregan los valores
                for i,j in itertools.product(range(m.shape[0]),range(m.shape[1])):
                    self.rows[i, j] = m[i, j]
                    self.shape = (max(self.shape[0], i + 1), max(self.shape[0], j + 1))

        def to_dense(self):
            r = np.zeros(self.shape)  # se llena la matriz de ceros
            for i, row in self.rows.items():  # se recorren las filas
              if isinstance(row, dict):
                for j, val in row.items():  # se recorren las columnas no nulas de la fila i
                    r[i, j] = val  # se agrega el valor en la posicion correspondiente

            return r



        def T(self):
            r = self.__class__(m=None)  # se crea el objeto sin argumentos
            for i, row in self.rows.items():  # se recorren las filas
                for j, val in row.items():  # se recorren las columnas
                    add_to_dict(r.rows, j, i, val)  # se agrega el valor transpuesto a la posicion correspondiente
                    r.shape = (max(r.shape[0], j + 1), max(r.shape[1], i + 1))  # se actualiza la forma de la matriz transpuesta
            return r



    return SparseMatrix3_class(**kwargs)

In [ ]:
import numpy as np

def random_sparse_matrix(size):
    m = np.random.randint(2, size=size)
    m = m * np.random.randint(15,size=size)
    return m

m = random_sparse_matrix((5,3)) # Filas, columnas
s = SparseMatrix3(m)

print(m)


[[ 3  6  2]
 [ 5  0 14]
 [11 11  4]
 [11  0  5]
 [ 0  1  0]]


In [ ]:
# 4. Método getitem

def SparseMatrix4(m=None, **kwargs):

    import itertools

    def add_to_dict(d, key1, key2, val):
        if key1 not in d:
            d[key1] = {}
        d[key1][key2] = val
        return d

    class SparseMatrix4_class:

        def __init__(self, m=m, **kwargs):
            self.rows = {} # diccionario de entradas no nulas de la matriz
            self.shape = (0,0)  # define el tamaño de la matriz
            if m is not None: # si m no es nula. m es la matriz y se le agregan los valores
                for i,j in itertools.product(range(m.shape[0]),range(m.shape[1])):
                    self.rows[i, j] = m[i, j]
                    self.shape = (max(self.shape[0], i + 1), max(self.shape[1], j + 1))

        def __getitem__(self, pos):
            i,j = pos
            assert isinstance(i, int) and isinstance(j, int), "Invalid index type"
            if 0 <= i < self.shape[0] and 0 <= j < self.shape[1]:
                return self.rows.get((i, j), 0)
            else:
                return 0

    return SparseMatrix4_class(**kwargs)

In [ ]:
def random_sparse_matrix(size):
    m = np.random.randint(2, size=size)
    m = m * np.random.randint(10,size=size)
    return m

m = random_sparse_matrix((5,3))

print("original matrix shape", m.shape)
print(m)

original matrix shape (5, 3)
[[0 0 9]
 [8 0 0]
 [8 0 4]
 [7 5 0]
 [1 4 0]]


In [ ]:
import itertools

s = SparseMatrix4(m)

print("inner dict", s.rows)
print("\ncoord   value_in_m       value_in_s")
for i,j in itertools.product(list(range(m.shape[0])), list(range(m.shape[1]))):
    print("(%d,%d)   %5d        %5d"%(i,j, m[i,j], s[i,j]))

inner dict {(0, 0): 0, (0, 1): 0, (0, 2): 9, (1, 0): 8, (1, 1): 0, (1, 2): 0, (2, 0): 8, (2, 1): 0, (2, 2): 4, (3, 0): 7, (3, 1): 5, (3, 2): 0, (4, 0): 1, (4, 1): 4, (4, 2): 0}

coord   value_in_m       value_in_s
(0,0)       0            0
(0,1)       0            0
(0,2)       9            9
(1,0)       8            8
(1,1)       0            0
(1,2)       0            0
(2,0)       8            8
(2,1)       0            0
(2,2)       4            4
(3,0)       7            7
(3,1)       5            5
(3,2)       0            0
(4,0)       1            1
(4,1)       4            4
(4,2)       0            0


In [ ]:
# 5. Método Setitem

def SparseMatrix5(m=None,**kwargs):

    import itertools
    import numpy as np

    def add_to_dict(d, key1, key2, val):
        if key1 not in d:
            d[key1] = {}
        d[key1][key2] = val
        return d

    class SparseMatrix5_class:

        def __init__(self, m=m, **kwargs):
            self.rows = {} # diccionario de entradas no nulas de la matriz
            self.shape = (0,0)  # define el tamaño de la matriz
            if m is not None: # si m no es nula. m es la matriz y se le agregan los valores
              for i,j in itertools.product(range(m.shape[0]),range(m.shape[1])):
                if m[i,j] != 0:
                    add_to_dict(self.rows, i, j, m[i, j])
                    self.shape = (max(self.shape[0], i + 1), max(self.shape[1], j + 1))

        def __setitem__(self, pos, val):
          i, j = pos
          assert isinstance(i, int) and isinstance(j, int), "Invalid index type"
          if 0 <= i < self.shape[0] and 0 <= j < self.shape[1]:
              if val != 0:
                  add_to_dict(self.rows, i, j, val)
              elif (i, j) in self.rows:
                  del self.rows[(i, j)]
          else:
              raise IndexError("Index out of range")

        def __getitem__(self, pos):
            i,j = pos
            assert isinstance(i, int) and isinstance(j, int), "Invalid index type"
            if 0 <= i < self.shape[0] and 0 <= j < self.shape[1]:
                return self.rows.get((i, j), 0)
            else:
                return 0

        def to_dense(self):
            r = np.zeros(self.shape)  # se llena la matriz de ceros
            for i, row in self.rows.items():  # se recorren las filas
                for j, val in row.items():  # se recorren las columnas no nulas de la fila i
                    r[i, j] = val  # se agrega el valor en la posicion correspondiente
            return r

    return SparseMatrix5_class(**kwargs)

In [ ]:
def random_sparse_matrix(size):
    m = np.random.randint(2, size=size)
    m = m * np.random.randint(10,size=size)
    return m

m = random_sparse_matrix((10,7))
s = SparseMatrix5(m)
print("initial")
print(s.rows)
print(s.to_dense().astype(int))
s[4,2] = m[4,2]*2+3
print("\nafter __setitem__")
print(s.rows)
print(s.to_dense().astype(int))

initial
{0: {3: 7, 4: 8, 6: 3}, 1: {1: 8, 4: 1, 5: 2, 6: 1}, 2: {0: 2, 3: 8, 4: 8, 6: 1}, 3: {1: 2, 3: 1, 4: 6}, 4: {1: 6, 2: 3, 4: 4}, 5: {0: 1, 1: 1, 2: 4}, 6: {2: 7, 4: 8, 6: 7}, 7: {0: 4, 1: 1, 2: 3, 4: 3}, 8: {0: 7, 2: 4, 4: 1}, 9: {2: 5, 4: 9}}
[[0 0 0 7 8 0 3]
 [0 8 0 0 1 2 1]
 [2 0 0 8 8 0 1]
 [0 2 0 1 6 0 0]
 [0 6 3 0 4 0 0]
 [1 1 4 0 0 0 0]
 [0 0 7 0 8 0 7]
 [4 1 3 0 3 0 0]
 [7 0 4 0 1 0 0]
 [0 0 5 0 9 0 0]]

after __setitem__
{0: {3: 7, 4: 8, 6: 3}, 1: {1: 8, 4: 1, 5: 2, 6: 1}, 2: {0: 2, 3: 8, 4: 8, 6: 1}, 3: {1: 2, 3: 1, 4: 6}, 4: {1: 6, 2: 9, 4: 4}, 5: {0: 1, 1: 1, 2: 4}, 6: {2: 7, 4: 8, 6: 7}, 7: {0: 4, 1: 1, 2: 3, 4: 3}, 8: {0: 7, 2: 4, 4: 1}, 9: {2: 5, 4: 9}}
[[0 0 0 7 8 0 3]
 [0 8 0 0 1 2 1]
 [2 0 0 8 8 0 1]
 [0 2 0 1 6 0 0]
 [0 6 9 0 4 0 0]
 [1 1 4 0 0 0 0]
 [0 0 7 0 8 0 7]
 [4 1 3 0 3 0 0]
 [7 0 4 0 1 0 0]
 [0 0 5 0 9 0 0]]


In [ ]:
#6 Implementar método add

def SparseMatrix6(m=None,**kwargs):

    import itertools
    import numpy as np
    def add_to_dict(d, key1, key2, val):
        if key1 not in d:
            d[key1] = {}
        d[key1][key2] = val
        return d

    class SparseMatrix6_class:

        def __init__(self, m=m, **kwargs):
            self.rows = {} # diccionario de entradas no nulas de la matriz
            self.shape = (0,0)  # define el tamaño de la matriz
            if m is not None: # si m no es nula. m es la matriz y se le agregan los valores
              for i,j in itertools.product(range(m.shape[0]),range(m.shape[1])):
                if m[i,j] != 0:
                    add_to_dict(self.rows, i, j, m[i, j])
                    self.shape = (max(self.shape[0], i + 1), max(self.shape[1], j + 1))

        def to_dense(self):
            r = np.zeros(self.shape)  # se llena la matriz de ceros
            for i, row in self.rows.items():  # se recorren las filas
                for j, val in row.items():  # se recorren las columnas no nulas de la fila i
                    r[i, j] = val  # se agrega el valor en la posicion correspondiente
            return r

        def __getitem__(self, pos):
            i,j = pos
            assert isinstance(i, int) and isinstance(j, int), "Invalid index type"
            if 0 <= i < self.shape[0] and 0 <= j < self.shape[1]:
                return self.rows.get((i, j), 0)
            else:
                return 0

        def __setitem__(self, pos, val):
          i, j = pos
          assert isinstance(i, int) and isinstance(j, int), "Invalid index type"
          if 0 <= i < self.shape[0] and 0 <= j < self.shape[1]:
              if val != 0:
                  add_to_dict(self.rows, i, j, val)
              elif (i, j) in self.rows:
                  del self.rows[(i, j)]
          else:
              raise IndexError("Index out of range")

        def __add__ (self, q):
            assert self.shape == q.shape, "Matrices must be of same shape"
            r = self.__class__(m=None)
            r.shape = self.shape
            for i, row in self.rows.items():
                  for j, val in row.items():
                      r[i, j] = val
            for i, row in q.rows.items():
                  for j, val in row.items():
                      r[i, j] += val
            return r

    return SparseMatrix6_class(**kwargs)

In [ ]:
import numpy as np
m1, m2 = random_sparse_matrix((5,3)), random_sparse_matrix((5,3))
sm1 = SparseMatrix6(m1)
sm2 = SparseMatrix6(m2)
print(sm1.to_dense().astype(int))
print("--")
print(sm2.to_dense().astype(int))

[[0 6 3]
 [0 6 0]
 [0 2 0]
 [7 0 0]
 [5 3 0]]
--
[[0 0 0]
 [0 0 0]
 [0 0 9]
 [6 0 7]
 [0 0 8]]


In [ ]:
print((sm1+sm2).to_dense().astype(int))

[[0 4 0]
 [6 4 0]
 [8 8 5]
 [6 2 5]
 [4 0 3]]


In [ ]:
print(m1+m2)

[[ 0 11  0]
 [ 7  4  0]
 [ 8 13  5]
 [ 7  2  5]
 [ 4  0  3]]


In [ ]:
#7. Implementacion del dot

def SparseMatrix7(m=None,**kwargs):

    import itertools
    import numpy as np
    def add_to_dict(d, key1, key2, val):
        if key1 not in d:
            d[key1] = {}
        d[key1][key2] = val
        return d

    class SparseMatrix7_class:

        def __init__(self, m=m, **kwargs):
            self.rows = {} # diccionario de entradas no nulas de la matriz
            self.shape = (0,0)  # define el tamaño de la matriz
            if m is not None: # si m no es nula. m es la matriz y se le agregan los valores
              for i,j in itertools.product(range(m.shape[0]),range(m.shape[1])):
                if m[i,j] != 0:
                    add_to_dict(self.rows, i, j, m[i, j])
                    self.shape = (max(self.shape[0], i + 1), max(self.shape[1], j + 1))

        def to_dense(self):
            r = np.zeros(self.shape)  # se llena la matriz de ceros
            for i, row in self.rows.items():  # se recorren las filas
                for j, val in row.items():  # se recorren las columnas no nulas de la fila i
                    r[i, j] = val  # se agrega el valor en la posicion correspondiente
            return r

        def __getitem__(self, pos):
            i,j = pos
            assert isinstance(i, int) and isinstance(j, int), "Invalid index type"
            if 0 <= i < self.shape[0] and 0 <= j < self.shape[1]:
                return self.rows.get((i, j), 0)
            else:
                return 0

        def __setitem__(self, pos, val):
          i, j = pos
          assert isinstance(i, int) and isinstance(j, int), "Invalid index type"
          if 0 <= i < self.shape[0] and 0 <= j < self.shape[1]:
              if val != 0:
                  add_to_dict(self.rows, i, j, val)
              elif (i, j) in self.rows:
                  del self.rows[(i, j)]
          else:
              raise IndexError("Index out of range")

        def __add__ (self, q):
            assert self.shape == q.shape, "Matrices must be of same shape"
            r = self.__class__(m=None)
            r.shape = self.shape
            for i, row in self.rows.items():
                  for j, val in row.items():
                      r[i, j] = val
            for i, row in q.rows.items():
                  for j, val in row.items():
                      r[i, j] += val
            return r

        def dot(self, q):
            assert self.shape[1] == q.shape[0], "Incompatible shapes"

            r = self.__class__(m=None)
            r.shape = (self.shape[0], q.shape[1])

            for i in range(self.shape[0]):
                for j in range(q.shape[1]):
                    r[i,j] = sum(self[i,k]*q[k,j] for k in range(self.shape[1]))


            return r

        def sparseness_metric(self):
            metric = 1 - len(self.rows) / (self.shape[0] * self.shape[1]) # calculo de la metrica, el 1 es una buena practica de python para que el numero sea un punto flotante
            return metric

        def T(self):
            r = self.__class__(m=None)  # se crea el objeto sin argumentos
            for i, row in self.rows.items():  # se recorren las filas
                for j, val in row.items():  # se recorren las columnas
                    add_to_dict(r.rows, j, i, val)  # se agrega el valor transpuesto a la posicion correspondiente
                    r.shape = (max(r.shape[0], j + 1), max(r.shape[1], i + 1))  # se actualiza la forma de la matriz transpuesta
            return r

    return SparseMatrix7_class(**kwargs)

In [ ]:
import numpy as np
m1 = np.random.randint(10, size=(3,2))
print (m1)
print("----")
m2 = np.random.randint(10, size=(2,3))
print (m2)
print ("-- ")
print (m1.dot(m2))
print("---")
s1 = SparseMatrix7(m1)
print("----")

s2 = SparseMatrix7(m2)
print("---")

print (s1.dot(s2).to_dense().astype(int))
print ("--")
print (m2.dot(m1))
print ("--")
print (s2.dot(s1).to_dense().astype(int))

[[9 7]
 [6 2]
 [9 7]]
----
[[2 0 3]
 [9 5 0]]
-- 
[[81 35 27]
 [30 10 18]
 [81 35 27]]
---
----
---
[[0 0 0]
 [0 0 0]
 [0 0 0]]
--
[[ 45  35]
 [111  73]]
--
[[0 0]
 [0 0]]


In [ ]:
#8. algoritmo que devuelva el valor máximo de cada fila.


def max_per_row(m):
    import numpy as np
    max_vals = {} # diccionario para almacenar el valor máximo y su índice de fila
    for (i,j), val in m.rows.items(): # iterar a través de los elementos no nulos de la matriz
        if i in max_vals: # si la fila ya ha sido encontrada, comparar con el valor máximo actual
            if val > max_vals[i][0]:
                max_vals[i] = (val, j)
        else:
            max_vals[i] = (val, j) # agregar nueva fila al diccionario

    return [(i, val[0]) for i,val in max_vals.items()] # devolver lista de tuplas de índices de fila y valor máximo


In [ ]:
m = random_sparse_matrix((10,4))
s = SparseMatrix3(m)
print(m)
print(max_per_row(s))

[[9 8 9 0]
 [2 0 0 0]
 [0 9 0 6]
 [0 0 8 0]
 [0 0 7 2]
 [0 0 0 0]
 [0 1 0 9]
 [1 0 8 9]
 [8 2 0 2]
 [0 3 0 7]]
[(0, 9), (1, 2), (2, 9), (3, 8), (4, 7), (5, 0), (6, 9), (7, 9), (8, 8), (9, 7)]


In [ ]:
mm = m.max(axis=1)
w = np.argwhere(mm!=0)[:,0]
np.allclose(np.r_[[(i,j) for i,j in zip(w, mm[w])]], np.r_[max_per_row(s)])

True

In [ ]:
def max_per_col(m):
    max_vals = {}
    for (i, j), val in m.rows.items():
        if j not in max_vals or val > max_vals[j]:
            max_vals[j] = val
    return [(j, val) for j, val in max_vals.items()]


In [ ]:
m = SparseMatrix3(random_sparse_matrix((3,10)))
print("Matriz dispersa:")
for i in range(m.shape[0]):
    for j in range(m.shape[1]):
        if (i,j) in m.rows:
            print(m.rows[i,j], end="\t")
        else:
            print(0, end="\t")
    print()

print("--------")

print (m.to_dense().astype(int))

print("--------")

print("Valores máximos de cada columna:")
print(max_per_col(m))

Matriz dispersa:
5	9	0	0	0	10	14	7	1	0	
8	6	1	12	0	7	0	0	12	11	
0	0	0	2	9	7	5	0	5	0	
--------
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
--------
Valores máximos de cada columna:
[(0, 8), (1, 9), (2, 1), (3, 12), (4, 9), (5, 10), (6, 14), (7, 7), (8, 12), (9, 11)]
